apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentalcars
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 267977387285.dkr.ecr.us-east-1.amazonaws.com/rentalcars:latest
          ports:
            - containerPort: 8080
